### ISSUE TITLE
ストリーム名の重複問題

### ISSUE THREAD

**Issue by hayate242** [ehimennlab/Panopticon#109]
## WHY
- 異なるユーザだと，同じストリーム名が使えてしまう

## WHAT
- 1ユーザーに対して1つのユニークStreamURLを割り振る

**Comment by MaineK00n** [comment]
ストリーム名ってこちらが用意するのではダメ？

**Comment by hayate242** [comment]
> ストリーム名ってこちらが用意するのではダメ？

たしかに、いちゆーざがそんなに同時に配信しないか

**Comment by hayate242** [comment]
そっちの方で解決するように変えます
