### ISSUE TITLE
Permission error with link on page after new registration

### ISSUE THREAD

**Issue by MaineK00n** [ehimennlab/Panopticon#145]
## WHY
A permission error occurs in the link on the page (see figure) that transitions after new registration.

![Screenshot from 2019-11-27 04-26-21](https://user-images.githubusercontent.com/16035056/69665629-1fbcdd80-10ce-11ea-856e-a919240e1466.png)

## WHAT
Analyze the cause of the permission error and fix it.

**Comment by MaineK00n** [comment]
The cause was a directory permission error.

**Comment by hayate242** [comment]
macでは，発生しないやつですね
