### ISSUE TITLE
videoとliveのDBを一つにまとめる

### ISSUE THREAD

**Issue by hayate242** [ehimennlab/Panopticon#276]
## WHAT
- テーブルを，VideosとStreamsを一つのテーブルにまとめる

**Comment by hayate242** [comment]
例えば，videosって言うテーブル一つにまとめるとすると
```
Schema::create('videos', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->bigInteger('user_id');
            $table->string('type'); // upload or liveを入れる
            $table->string('title')->uniqe()->charset('utf8');
            $table->string('description', 2000)->charset('utf8');
            $table->integer('scope');
            $table->string('key')->uniqe()->charset('utf8');
            $table->timestamps();
        })
``
となると思うんですけど，ページでLive一覧とか，アップロード動画一覧をそれぞれ表示するときに
typeをキーにしてデータを取り出す必要があって，それだと動画の数が増えると検索に時間かかっちゃいそうな気がするんですけど
どう思います？

**Comment by MaineK00n** [comment]
雑にやるならタイムスタンプ最新から何件とかは？

**Comment by MaineK00n** [comment]
これはどこのページを想定していますか？
動画の検索機能が無いので，ホームページに全部表示することになりそうですが
> ページでLive一覧とか，アップロード動画一覧をそれぞれ表示するときに

**Comment by MaineK00n** [comment]
そうするとどれをキーにしても変わらない気がします

**Comment by MaineK00n** [comment]
https://github.com/ehimennlab/Panopticon/issues/276#issuecomment-611985500

この発言を受け取ると，`type` は他の用途に使う予定だったように感じますが，どうなのでしょうか？

**Comment by hayate242** [comment]
> [#276 (comment)](https://github.com/ehimennlab/Panopticon/issues/276#issuecomment-611985500)
> 
> この発言を受け取ると，`type` は他の用途に使う予定だったように感じますが，どうなのでしょうか？

typeはliveかuploadを分類するのに使う予定でした

**Comment by hayate242** [comment]
> 雑にやるならタイムスタンプ最新から何件とかは？

それは採用したい

**Comment by MaineK00n** [comment]
だとすると，このissueの意味が分からないところですが
> テーブルを，VideosとStreamsを一つのテーブルにまとめる

**Comment by hayate242** [comment]
ちょっとわからなくなってきたのでもう一度整理すると，
このissueをたてたのは，確かどこかのPRのコメントで @MaineK00n が
VideosとStreamsの構造がほとんど一緒だから一つにまとめた方がいいのでは
みたいな話があって，とりあえずissue化したのですが

**Comment by hayate242** [comment]
とすると，対応不要？？

**Comment by MaineK00n** [comment]
https://github.com/ehimennlab/Panopticon/pull/130/files#r399139969
このあたりをTODOにしていたので，issueにすることを推奨したわけです．
確かにDBのVideosとStreamsの設計をhangoutかなにかで聞いたときに，分けている必要性を感じられる解答が得られなかったので，合わせても良いのではと提案したと思います．

https://github.com/ehimennlab/Panopticon/blob/hayate242/%23284/src/php/database/migrations/2019_10_02_114325_create_streams_table.php
```
Schema::create('streams', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->bigInteger('user_id');
            $table->string('title')->uniqe()->charset('utf8');
            $table->string('description', 2000);
            $table->string('key')->uniqe()->charset('utf8');
            $table->timestamps();
        });
```

https://github.com/ehimennlab/Panopticon/blob/hayate242/%23284/src/php/database/migrations/2019_12_02_130902_create_videos_table.php
```
Schema::create('videos', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->bigInteger('user_id');
            $table->string('title')->uniqe()->charset('utf8');
            $table->string('description', 2000)->charset('utf8');
            $table->integer('scope');
            $table->string('fpath', 255);
            $table->string('original_filename', 255);
            $table->timestamps();
        });
```

**Comment by MaineK00n** [comment]
`type` が明確に何をするものか理解していないときにissueの話をしたため，こういうことになっているのかもしれません

**Comment by MaineK00n** [comment]
明確に分けておきたい理由があるならば，それを聞きたいです

**Comment by hayate242** [comment]
自分の中では，Live一覧とUpload一覧は別々で表示しようと思ってたので，別のテーブルにしておく方がいいかなと思ってたんですが
一緒にした方が良さそうですね

**Comment by MaineK00n** [comment]
別に表示しても良いと思います
Youtubeはトップだとごちゃまぜで，niconicoだと分けているわけなので，表示を別にしたいという理由は1つあると思います．
その上で，DBの内容がそこまで変わらないので，合わせても問題ない気がしたわけです．さらに，件数が多くなったとしても，リコメンドシステムやランキングシステムも実装されていないので，おそらくタイムスタンプが有効になると思いますが，いかがでしょうか？

**Comment by hayate242** [comment]
> 別に表示しても良いと思います
> Youtubeはトップだとごちゃまぜで，niconicoだと分けているわけなので，表示を別にしたいという理由は1つあると思います．
> その上で，DBの内容がそこまで変わらないので，合わせても問題ない気がしたわけです．さらに，件数が多くなったとしても，リコメンドシステムやランキングシステムも実装されていないので，おそらくタイムスタンプが有効になると思いますが，いかがでしょうか？

そうですね，結構変更点多そうですが，DBの統合やってみます！

**Comment by hayate242** [comment]
不要になったので，クローズします
